### ISSUE TITLE
FR: Add feature to add custom instructions to chatgpt

### ISSUE THREAD

**Issue by tomasrei** [MichelNivard/gptstudio#121] opened 2023-07-02 13:00 UTC
Great package! I was thinking that it would be great if you could add some custom/default prompts, so that interactions become more efficient. For example, I add "only code, no comments" at the end of many prompts.

Cheers,
Tom

**Comment by JamesHWade** [comment] 2023-07-03 22:28
Thank you for the suggestion!

**Comment by calderonsamuel** [comment] 2023-07-05 00:25
I think this is a duplicate of #86

**Closed** 2023-07-05 20:54 UTC
Labels: feature
