### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by stephando** [MichelNivard/GPTstudio#2] opened 2022-12-26 07:59 UTC
thanks very much for this package Michel. Tried to install with the below error log. Maybe you have an idea how to fix it. Many thanks - Stephan

> require(devtools)
> install_github("MichelNivard/GPTstudio")
Downloading GitHub repo MichelNivard/GPTstudio@HEAD
✔  checking for file ‘/private/var/folders/fg/96hc1rp50bn9zl8xbdg15yp40000gn/T/RtmpHHm4N7/remotes675e6dfc4aad/MichelNivard-GPTstudio-f4b4638/DESCRIPTION’ ...
─  preparing ‘GPTstudio’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘GPTstudio_0.1.0.tar.gz’
   
* installing *source* package ‘GPTstudio’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘openai’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘GPTstudio’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/GPTstudio’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/fg/96hc1rp50bn9zl8xbdg15yp40000gn/T//RtmpHHm4N7/file675e4e8adc44/GPTstudio_0.1.0.tar.gz’ had non-zero exit status

**Comment by MichelNivard** [comment] 2022-12-26 08:08
It’s a failure to instal “openai” which is an R package I depend on. You could try and install that manually first. I see if I have time to debug further later today

**Comment by fabiogiglietto** [comment] 2022-12-26 09:16
Got the same error but installing the openai package manually worked for me.

**Comment by jhelvy** [comment] 2022-12-26 11:40
Same here - manually installed `openai` and it worked. 

Perhaps the issue is the indentation on `Imports:` in the description file? 

https://github.com/MichelNivard/GPTstudio/blob/main/DESCRIPTION#L8

**Comment by JamesHWade** [comment] 2022-12-26 12:01
I think you're right @jhelvy. #1 should fix this.

**Comment by MichelNivard** [comment] 2022-12-26 12:48
Okay, let's see if this fixes it, I think it does!

**Comment by MichelNivard** [comment] 2022-12-26 15:25
As far as I can tell James pull request fixed this issue, closing…

**Closed by MichelNivard** 2022-12-26 15:25 UTC
