### ISSUE TITLE
Unable to connect to Azure OpenAI

### ISSUE THREAD

**Issue by EdwardJ1n** [MichelNivard/gptstudio#161] opened 2023-12-27 14:02 UTC
Hi team, 

Hope this message finds you well. 

We've met an issue to use Azure OpenAI as follows when starting ChatGPT addins: 
```
Loading required package: shiny

Listening on http://127.0.0.1:7490
! OPENAI_API_KEY is not valid.
ℹ Generate a key at <https://platform.openai.com/account/api-keys>
ℹ Set the key in your .Renviron file usethis::edit_r_environ()
Warning: Error in httr2::req_perform: HTTP 401 Unauthorized.
...
```

May I ask how we can direct gptstudio to connect to Azure OpenAI instead of OpenAI? 

Setting ~/.Renviron as follows
```
AZURE_OPENAI_TASK="completions"
AZURE_OPENAI_ENDPOINT="XXXX"
AZURE_OPENAI_DEPLOYMENT_NAME="XXXX"
AZURE_OPENAI_KEY="XXXX"
AZURE_OPENAI_API_VERSION="2023-12-01-preview"
```

Much appreciated, 
Edward

**Comment by calderonsamuel** [comment] 2023-12-27 15:09
Please try with the development version:

```r
# install.packages("pak")
pak::pak("MichelNivard/gptstudio")
```

Let us know if that worked better

**Comment by EdwardJ1n** [comment] 2023-12-28 00:07
Hi Samuel, 

Thanks for your prompt reply. 

This is how we install it. 
```
install.packages("pak")
pak::pak("MichelNivard/gptstudio")

packageVersion("gptstudio")
[1] ‘0.3.1.9000’
```
> Please try with the development version:
> 
> ```r
> # install.packages("pak")
> pak::pak("MichelNivard/gptstudio")
> ```
> 
> Let us know if that worked better

Thanks, 
Edward

**Comment by calderonsamuel** [comment] 2023-12-28 13:33
Ok. After installing the development version you are still having the same problem?

This part of the error message :

```
Warning: Error in httr2::req_perform: HTTP 401 Unauthorized.
```

Means that you are attempting to use an unauthorized key/token. Are you sure you have the correct permissions to use that endpoint/deployment? Can they charge you money/credits to use it?

**Comment by EdwardJ1n** [comment] 2023-12-28 15:24
> Ok. After installing the development version you are still having the same problem?
> 
> This part of the error message :
> 
> ```
> Warning: Error in httr2::req_perform: HTTP 401 Unauthorized.
> ```
> 
> Means that you are attempting to use an unauthorized key/token. Are you sure you have the correct permissions to use that endpoint/deployment? Can they charge you money/credits to use it?

Hey Samuel, 

Thanks for looking into it. 

We are using Azure OpenAI, and our end point looks like: 
```
AZURE_OPENAI_ENDPOINT="https://XXXX.openai.azure.com/"
```
However, the message said: 
```
Loading required package: shiny

Listening on http://127.0.0.1:7490
! OPENAI_API_KEY is not valid.
ℹ Generate a key at <https://platform.openai.com/account/api-keys> <=== OpenAI URL, instead of Azure OpenAI. 
ℹ Set the key in your .Renviron file usethis::edit_r_environ()
Warning: Error in httr2::req_perform: HTTP 401 Unauthorized.
```

Apparently, it has connected to OpenAI instead of *Azure OpenAI*. 
The environment variables that we provided is used to connect to Azure OpenAI. 

Looks like OpenAI URL is hard-coded. 
May I ask how to select Azure OpenAI connection? 

Thanks a lot. 
Edward

**Comment by calderonsamuel** [comment] 2023-12-28 16:58
Ok. I was able to reproduce this after removing OPENAI_API_KEY in my user's .Renviron file. 

You are rigth, this should not be happening. I'll make a fix for this. In the meantime you can manually fix it by following this steps:

- Open your gptstudio config file. For that, you can execute this in your Rstudio console:

```r
config_dir <- tools::R_user_dir("gptstudio", which = "config")
config_file <- file.path(config_dir,"config.yml")

tryCatch({
	rstudioapi::navigateToFile(config_file)
}, error = function(e){
	dir.create(path = config_dir, recursive = TRUE)
	file.create(config_file)
	rstudioapi::navigateToFile(config_file)
})
```

It should open a file. 

- **If the file is empty**, paste this and modify the model name. I think it should be the same as your deployment name. Quotes are not mandatory here, but they also shouldn't be harmful. **If the file is not empty**, focus on *service* and *model*. Service should be changed to "azure_openai" and model should also be changed to the deployment name.

```yaml
code_style: tidyverse
skill: beginner
task: coding
language: en
service: azure_openai
model: model-name
custom_prompt: You are a helpful assistant.
stream: 'TRUE'
```

- Save the changes to the file. Restart the R session and try running the addin. 

Let me know if that works. And if it does, don't close the issue as we will use it to track the fix of this bug.

**Comment by EdwardJ1n** [comment] 2023-12-29 01:03
Hey Samuel, 

After making the change, it looks loading Azure OpenAI. And, the UI is shown with message "No models available". 
As checked, it is an available model/deployment in Azure OpenAI. I can use it in python code. 
the config.xml looks this. 
```
code_style: tidyverse
skill: beginner
task: coding
language: en
service: azure_openai
model: gpt4
custom_prompt: You are a helpful assistant.
stream: 'TRUE'
```
the UI is shown with message "No models available". 
```
Loading required package: shiny
Warning in readLines(file, warn = readLines.warn) :
  incomplete final line found on '/home/edward.jin@beigenecorp.net/.config/R/gptstudio/config.yml'

Listening on http://127.0.0.1:3672
$messages
$messages[[1]]
$messages[[1]]$role
[1] "system"
$messages[[1]]$content
As a chat bot assisting an R programmer working in the RStudio IDE, it is important to tailor responses to their skill level and preferred coding style. They consider themselves to be a beginner R programmer. Provide answers with their skill level in mind. They prefer to use a tidyverse style of coding. When possible, answer code questions using tidyverse, r-lib, and tidymodels family of packages. R for Data Science is also a good resource to pull from. 
$messages[[2]]
$messages[[2]]$role
[1] "user"
$messages[[2]]$content
[1] "Write a R script to calculate the medium number from an array. "
Warning: Error in query_api_azure_openai: ✖ Azure OpenAI API request failed. Error 400 - Bad Request
ℹ Visit the Azure OpenAi Error code guidance for more details
ℹ You can also visit the API documentation
  87: <Anonymous>
  78: gptstudio_response_process
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
```

Then, I changed the service value from "service: azure_openai" to "service: azure". 
It prompted "Got models!". And, I tried to input a prompt. The UI is gone, and I got the message below from the Background Jobs. 
```
Loading required package: shiny
Warning in readLines(file, warn = readLines.warn) :
  incomplete final line found on '/home/edward.jin@beigenecorp.net/.config/R/gptstudio/config.yml'

Listening on http://127.0.0.1:7872
Warning: Error in : API key is not valid
  85: <Anonymous>
  78: gptstudio_skeleton_build
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
```
I think that the login is complete, but when running a prompt, it still try to call OpenAI REST API, but this is only my 2 cents. 

Can you take a look at it? 

Many thanks, 
Edward

**Comment by calderonsamuel** [comment] 2024-01-11 15:33
Hi @EdwardJ1n , sorry for the super late response. This is kind-of a post-mortem for the problem.

The new error you see happens because we call an internal function called `get_available_models()` that will give the list of models available for each service. Because azure-openai deployments can have custom names, we don't provide a list of them.  This means that, in practice, azure-openai is not currently supported. Let me be super clear: this is bad, we thought we were supporting it!

I think I can have a fix for this by the end of the day, but be aware that the way we read settings might slightly change in the near future (#164 ), so it might break again soon but only once, to evolve into a stable version.

**Closed** 2024-01-11 18:06 UTC

**Comment by calderonsamuel** [comment] 2024-01-11 23:11
This should be fixed now! Please @EdwardJ1n let us know if it's working on your side. 

```r
# install.packages("pak")
pak::pak("MichelNivard/gptstudio")
```

**Comment by EdwardJ1n** [comment] 2024-01-12 02:56
Hi Michel,

Hope you have a good holiday.

Thanks a lot for looking into.

For the latest version of OpenAI SDK, I think taht the common model name will be supported for Azure OpenAI. E.g, the deployment name is gpt4-t for gpt4-turbo model, and we can use gpt4-tubo directly now.
[cid:3e4b6d91-013a-4262-98af-b055bc15c0fa]

Looking forward to the updated version.

Best Regards
Edward

________________________________
发件人: Samuel Calderon ***@***.***>
发送时间: 2024年1月11日 23:33
收件人: MichelNivard/gptstudio ***@***.***>
抄送: Edward Jin ***@***.***>; Mention ***@***.***>
主题: Re: [MichelNivard/gptstudio] Unable to connect to Azure OpenAI (Issue #161)


Hi @EdwardJ1n<https://github.com/EdwardJ1n> , sorry for the super late response. This is kind-of a post-mortem for the problem.

The new error you see happens because we call an internal function called get_available_models() that will give the list of models available for each service. Because azure-openai deployments can have custom names, we don't provide a list of them. This means that, in practice, azure-openai is not currently supported. Let me be super clear: this is bad, we thought we were supporting it!

I think I can have a fix for this by the end of the day, but be aware that the way we read settings might slightly change in the near future (#164<https://github.com/MichelNivard/gptstudio/issues/164> ), so it might break again soon but only once, to evolve into a stable version.

―

**Comment by jorgesinval** [comment] 2024-07-06 08:14
Hello.

I am also trying to Azure OpenAI. I instaled `gptstudio` development version.

After configuring `.Renviron` and running the addin I get:

```
ℹ Fetching models for azure_openai service...
✔ Got models!
Warning: Error in : API key is not valid
  85: <Anonymous>
  78: gptstudio_skeleton_build
  76: observe
  75: <observer>
   4: shiny::runApp
   3: eval
   2: eval
   1: .rs.sourceWithProgress
```
